export const CATEGORIAS_UNIFORMES: Record<string, string[]> = {
  'CRECHE': [
    'CONJUTO CAMISETA BEBÊ E TAPA FRALDA',
    'CONJUTO CAMISETA E BERMUDA',
    'VESTIDO FEMININO COM TAPA FRALDA',
    'CONJUNTO MOLETON BEBÊ',
    'MEIA ANTIDERRAPENTE'
  ],
  'PRÉ ESCOLA': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'CAMISETA MANGA LONGA',
    'BERMUDA HELANCA (MENINOS)',
    'SHORT SAIA HELANCA (MENINAS)',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL'
  ],
  'FUNDAMENTAL 1-3 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'CAMISETA MANGA LONGA',
    'BERMUDA HELANCA (MENINOS)',
    'SHORT SAIA HELANCA (MENINAS)',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL'
  ],
  'FUNDAMENTAL 4-5 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'BERMUDA MASCULINA TACTEL',
    'BERMUDA LEGGINS FEMIN.',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL'
  ],
  'FUNDAMENTAL II 6 AO 9 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'BERMUDA MASCULINA TACTEL',
    'BERMUDA LEGGINS FEMININA',
    'JAQUETA MICROFIBRA',
    'CALÇA JEAND MASC.',
    'CALÇA JEAND FEMIN.',
    'MEIA COLEGIAL'
  ],
  'EJA': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'JAQUETA MICROFIBRA',
    'MEIA COLEGIAL',
    'CALÇA JEAND MASC.',
    'CALÇA JEAND FEMIN.ACINT.'
  ]
};

export const TAMANHOS_DISPONIVEIS = [
  '1', '2', '3', '4', '6', '8', '10', '12', '14', '16', 'P', 'M', 'G', 'GG', 'EG', 'OUTROS'
];

export const UNIDADES_MEDIDA = [
  'CONJ.', 'PAR', 'UNIT.', 'PEÇ.', 'PCT', 'OUTROS'
];

export const SEGMENTOS_ENSINO = [
  'CONJUNTO UNIFORMA ESCOLAR CRECHE',
  'CONJUNTO UNIFORMA ESCOLAR PRÉ ESCOLA',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL 1-3 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL 4-5 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL II 6 AO 9 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR EJA'
];
