export const CATEGORIAS_UNIFORMES: Record<string, string[]> = {
  'CRECHE': [
    'CONJUTO CAMISETA BEBÊ E TAPA FRALDA',
    'CONJUTO CAMISETA E BERMUDA',
    'VESTIDO FEMININO COM TAPA FRALDA',
    'CONJUNTO MOLETON BEBÊ',
    'MEIA ANTIDERRAPENTE',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ],
  'PRÉ ESCOLA': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'CAMISETA MANGA LONGA',
    'BERMUDA HELANCA (MENINOS)',
    'SHORT SAIA HELANCA (MENINAS)',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ],
  'FUNDAMENTAL 1-3 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'CAMISETA MANGA LONGA',
    'BERMUDA HELANCA (MENINOS)',
    'SHORT SAIA HELANCA (MENINAS)',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ],
  'FUNDAMENTAL 4-5 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'CAMISETA MANGA LONGA',
    'BERMUDA MASCULINA TACTEL',
    'BERMUDA LEGGINS FEMIN. (TAPA BUMBUM)',
    'CONJUNTO DE JAQUETA (FORRADO) E CALÇA EM MICROFIBRA',
    'MEIA COLEGIAL',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ],
  'FUNDAMENTAL II 6 AO 9 ANOS': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'BERMUDA MASCULINA TACTEL',
    'BERMUDA LEGGINS FEMIN. (TAPA BUMBUM)',
    'JAQUETA MICROFIBRA',
    'CALÇA JEAND MASC.',
    'CALÇA JEAND FEMIN.',
    'MEIA COLEGIAL',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ],
  'EJA': [
    'CAMISETA COM MANGA',
    'CAMISETA SEM MANGA',
    'JAQUETA MICROFIBRA',
    'MEIA COLEGIAL',
    'CALÇA JEAND MASC.',
    'CALÇA JEAND FEMIN.ACINT.',
    'TÊNIS FECHAMENTO COM CADARÇO',
    'TÊNIS FECHAMENTO COM VELCRO'
  ]
};

export const TAMANHOS_DISPONIVEIS = [
  '1', '2', '3', '4', '6', '8', '10', '12', '14', '16',
  '18', '20', '22', '24', '26', '28', '30', '32', '34', '36', '38', '40', '42', '44', '46', '48', '52',
  'P', 'M', 'G', 'GG', 'EG', 'OUTROS'
];

export const UNIDADES_MEDIDA = [
  'CONJ.', 'PAR', 'UNIT.', 'PEÇ.', 'PCT', 'OUTROS'
];

export const SEGMENTOS_ENSINO = [
  'CONJUNTO UNIFORMA ESCOLAR CRECHE',
  'CONJUNTO UNIFORMA ESCOLAR PRÉ ESCOLA',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL 1-3 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL 4-5 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR FUNDAMENTAL II 6 AO 9 ANOS',
  'CONJUNTO UNIFORMA ESCOLAR EJA'
];
